### ISSUE TITLE
Would it be possible to get an update to version  7?

### ISSUE THREAD

**Issue by simkessy** [maxigs/formvalidation-rails#2]
This is the version I'm seeing: v0.6.2-dev, built on 2015-03-13 8:15:45 AM

**Comment by maxigs** [comment]
Hi, sorry for the late answer but i'm pretty swamped at the moment. I'll have a look a.s.a.p. but can't make any promise when i'll get around to upgrading it. 
If you are in a rush feel free to send a pull request and ill upgrade the gem (or you can also use a git-repo via bundler directly), normally the upgrade should be rather easy, just replacing the js files with the latest.

**Comment by simkessy** [comment]
Turns out it's not free anymore so I'm not sure how that would work. It's fine though. This version is working perfectly good anyways. Thx.

**Comment by maxigs** [comment]
The Version 6.x was also NOT free for commercial usage (see the license part in the readme) , open source does not mean it's always free to use in any way ;)
