### ISSUE TITLE
works on localhost, not in production

### ISSUE THREAD

**Issue by asalgan** [maxigs/formvalidation-rails#5]
This gem works great on localhost but doesn't seem to do anything in production, I included the necessary files in the asset pipeline. Any ideas why this may be happening?

**Comment by maxigs** [comment]
Hi Alan, does your asset:precompile - or however your project handles the assets - work properly?

Can you check if the JS/CSS of the project are in your projects application.js/css for production?

Other than that i can't think of any reason why it would not work, not much code that could go wrong.
It's only a couple of files added to the asset pipeline.

**Comment by asalgan** [comment]
Yep all my assets precompile successfully except for these.

**Comment by maxigs** [comment]
Do you have any more information for this?

So far i'm kinda in the dark as to what could cause this issue.

**Comment by asalgan** [comment]
Sorry about that, I actually had a javascript error that wasn't showing up in my console, the gem works great. Thank you very much for looking into it

**Comment by maxigs** [comment]
:) no worries
